apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../rbac
- ../../manager

namespace: client-namespace-changeit

patches:
- path: ./operator-env-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: redis-operator
    version: v1
- path: ./operator-deployment-patch.yaml
