# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ./operator-deployment-patch.yaml  

resources:
- resources/namespace.yaml
- ../samples
- ../rbac
- ../manager

