apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ./operator-deployment-patch.yaml  

resources:
- resources/namespace.yaml
- ../samples
- ../rbac
- ../manager

