# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

namespace: default

resources:
- operator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - redkey_operator_config.yaml
  name: redkey-operator-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


