apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redkey-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redkey-operator-role
subjects:
- kind: ServiceAccount
  name: redkey-operator-sa
  namespace: default
