# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view redkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redkeycluster-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters/status
  verbs:
  - get
