# permissions for end users to edit redkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redkeycluster-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters/status
  verbs:
  - get
