# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redkey-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redkey-operator-role
subjects:
- kind: ServiceAccount
  name: redkey-operator-sa
  namespace: default
