# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view redkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: redkeycluster-viewer-role
rules:
- apiGroups:
  - redkey.inditex.dev
  resources:
  - redkeyclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redkey.inditex.dev
  resources:
  - redkeyclusters/status
  verbs:
  - get
