# permissions for end users to view redkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: redkeycluster-viewer-role
rules:
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters/status
  verbs:
  - get
