# permissions for end users to edit redkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: redkeycluster-editor-role
rules:
- apiGroups:
  - redidev
  resources:
  - redkeyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.inditex.dev
  resources:
  - redkeyclusters/status
  verbs:
  - get
