apiVersion: apps/v1
kind: Deployment
metadata:
  name: redkey-operator
  labels:
    control-plane: redkey-operator
spec:
  template:
    spec:
      containers:
        - name: redkey-operator
          resources:
            requests:
              cpu: 0.3
              memory: 200Mi
