apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: ./robin-patch.yaml
  target:
    kind: RedKeyCluster
    name: redis-cluster-ephemeral

resources:
- ../ephemeral

namespace: redkey-operator