apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/redis.inditex.dev_redkeyclusters.yaml

patches:
- path: ./patches/operator-crd-patch.yaml
- path: ./patches/webhook_in_redkeyclusters.yaml
