# This NetworkPolicy allows ingress traffic to your webhook server running
# as part of the controller-manager from specific namespaces and pods. CR(s) which uses webhooks
# will only work when applied in namespaces labeled with 'webhook: enabled'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: redkey-cluster-operator
  name: allow-webhook-traffic
  namespace: redis-operator
spec:
  podSelector:
    matchLabels:
      control-plane: redis-operator-webhook
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - protocol: TCP
        port: 9443
