apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: redis-operator-webhook
  name: redis-operator-webhook
  namespace: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: redis-operator-webhook
  template:
    metadata:
      labels:
        control-plane: redis-operator-webhook
        domain: DOMAIN
        environment: ENVIRONMENT
        layer: middleware-redisoperator-webhook
        slot: default
        tenant: TENANT
        type: middleware
    spec:
      containers:
      - command:
        - /webhook
        image: redis-operator-webhook
        imagePullPolicy: Always
        name: redis-operator-webhook
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.3"
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: redis-operator-sa
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: redis-operator-webhook-service-cert
