# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

- op: remove
  path: /spec/template/spec/containers/0/livenessProbe
- op: remove
  path: /spec/template/spec/containers/0/readinessProbe
- op: replace
  path: /spec/template/spec/containers/0/env
  value:
  - name: WATCH_NAMESPACE
    value: watch-namespace
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always