# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

- op: add
  path: /spec/robin/template/spec/containers/0/command
  value:
  - "sleep"
  - "18000"
- op: replace
  path: /spec/robin/template/spec/containers/0/imagePullPolicy
  value: Always
- op: add
  path: /spec/robin/template/spec/containers/0/ports
  value:
    - containerPort: 8080
      name: prometheus
      protocol: TCP
    - containerPort: 40000
      name: debug
      protocol: TCP